name: CI

on:
  push:
    branches:
      - master
      - next
      - 'release-*'
      - 'v*'
  pull_request: {}

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: wyvox/action@v1

      - name: install dependencies
        run: pnpm i
        env:
          CI: true
      - run: pnpm run lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: wyvox/action@v1

      - name: install dependencies
        run: pnpm i
        env:
          CI: true

      - run: pnpm test
